// AUTO-GENERATED by scripts/generate-api-types.ts — DO NOT EDIT BY HAND
// Snapshot: AstraOS API v0.1.0
//
// Runtime-validated companion lives in src/lib/schemas.ts (Zod types that
// mirror backend Pydantic schemas).  This module provides a second layer of
// typings derived directly from the backend OpenAPI spec so we can detect
// drift in CI via a type-equivalence test.

export type SpecTitle = "AstraOS API";
export type SpecVersion = "0.1.0";

export interface SpecPaths {
  "/v1/health/livez": { methods: "get" };
  "/v1/health/readyz": { methods: "get" };
  "/v1/health": { methods: "get" };
  "/v1/kernel/state": { methods: "get" };
  "/v1/kernel/stats": { methods: "get" };
  "/v1/kernel/traces": { methods: "get" };
  "/v1/auth/login": { methods: "post" };
  "/v1/auth/me": { methods: "get" };
  "/v1/auth/refresh": { methods: "post" };
  "/v1/observability/summary": { methods: "get" };
  "/health/livez": { methods: "get" };
  "/health/readyz": { methods: "get" };
  "/health": { methods: "get" };
}
