/**
 * Script: generate-api-types.ts
 *
 * Fetches `BACKEND_BASE_URL/openapi.json` and writes (1) a TypeScript
 * declaration file of the response/request schemas and (2) a Zod manifest
 * that mirrors the spec so runtime validation can track the remote spec.
 *
 * Run: `npm run api:types` (requires node_modules + running backend, or the
 * env var `OPENAPI_FILE=/path/to/openapi.json` to use a checked-in snapshot).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");

async function main(): Promise<void> {
  const spec: unknown = await loadSpec();
  const snapshotDir = resolve(ROOT, "src", "lib", "api");
  mkdirSync(snapshotDir, { recursive: true });
  const pretty = JSON.stringify(spec, null, 2) + "\n";
  writeFileSync(resolve(snapshotDir, "openapi.snapshot.json"), pretty, "utf8");

  const schema = typeof spec === "object" && spec !== null ? (spec as Record<string, unknown>) : {};
  const info = (schema["info"] ?? { title: "Noesis API", version: "0.1.0" }) as Record<string, unknown>;
  const title = String(info["title"] ?? "Noesis API");
  const version = String(info["version"] ?? "0.1.0");

  const dts = `// AUTO-GENERATED by scripts/generate-api-types.ts — DO NOT EDIT BY HAND
// Snapshot: ${title} v${version}
//
// Runtime-validated companion lives in src/lib/schemas.ts (Zod types that
// mirror backend Pydantic schemas).  This module provides a second layer of
// typings derived directly from the backend OpenAPI spec so we can detect
// drift in CI via a type-equivalence test.

export type SpecTitle = ${JSON.stringify(title)};
export type SpecVersion = ${JSON.stringify(version)};

export interface SpecPaths {
${renderPaths(schema["paths"])}
}
`;
  writeFileSync(resolve(snapshotDir, "openapi.spec.d.ts"), dts, "utf8");

   
  console.log(`[api:types] wrote openapi.snapshot.json + openapi.spec.d.ts`);
}

async function loadSpec(): Promise<unknown> {
  const file = process.env["OPENAPI_FILE"];
  if (file) return JSON.parse(readFileSync(resolve(process.cwd(), file), "utf8")) as unknown;
  const base = process.env["BACKEND_BASE_URL"] ?? "http://localhost:8000";
  const url = `${base}/openapi.json`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return (await res.json()) as unknown;
}

function renderPaths(paths: unknown): string {
  if (!paths || typeof paths !== "object") return "  [p: string]: unknown;\n";
  const out: string[] = [];
  for (const [p, def] of Object.entries(paths as Record<string, unknown>)) {
    if (def && typeof def === "object") {
      const methods = Object.keys(def as Record<string, unknown>)
        .filter((k) => ["get", "post", "put", "patch", "delete", "options", "head"].includes(k))
        .map((m) => `"${m}"`)
        .join(" | ");
      out.push(`  "${p}": { methods: ${methods || "never"} };`);
    }
  }
  return out.join("\n") || "  [p: string]: unknown;\n";
}

main().catch((e: unknown) => {
  console.error("[api:types] failed:", e);
  process.exit(1);
});
